### ISSUE TITLE
FeatureRequest - shows protocol used in the profiler

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/neo4j-symfony#18]
Would be nice to see in the profiler if the query was sent with http or bolt

**Comment by Nyholm** [comment]
If we should be able to show info about the connection we need to send the Connection object with the `PreRunEvent`. Is it okey if I update the Neo4jClient's events for this feature? Does it makes sense from the domain perspective?

**Comment by ikwattro** [comment]
This makes events very heavy. You can easily guess the connection by checking the namespace of the Result class

**Comment by Nyholm** [comment]
I did not know. Thank you!
