### ISSUE TITLE
Inquiry: Do all AJAX (query) requests take >1000ms?

### ISSUE THREAD

**Issue by sfdreverman** [neo4j-contrib/neo4j-symfony#32]
Hi, 

Just checking here: Do all, except one ;-) , AJAX (query) requests normally take >1000ms?
My Neo4j version is 3.2 CE and I'm running it locally from the command-line, since it is the zip package.
The rest of the repo is untouched.

![image](https://cloud.githubusercontent.com/assets/7303997/26596382/d0e3bcce-456e-11e7-9981-c82523b5019d.png)

Thanks in advance,

Stefan

**Comment by Nyholm** [comment]
Not sure. Click on the profile for each call and see whats happening. 

Since you are running in dev it will take **a lot** more time that it does in prod.

**Comment by jexp** [comment]
I presume that you don't have an index on `:Movie(title)` ? 

Also for the first few requests you pay a bit of a warmup cost.

**Comment by sfdreverman** [comment]
The truth is that I haven't optimized anything. That's correct. The reason I'm asking is this:
- In my own project I have a query that yields 6 nodes with 3-4 attributes each, no relations.
- the query is: MATCH (n:InfoType) RETURN n ORDER BY n.name
- Neo4j browser returns the result in 15ms
- Symfony with Graphaware or Neo4jBundle connector returns in >1000ms

What strikes me is the difference between a browser query and the symfony query is +1000ms. 

So far, any query to Neo4j (in dev env) takes >1000ms as indicated by the symfony profiler (Neo4j tab). Unfortunately, the AJAX calls in the movies project do not yield a Neo4j profiler result.

I guess I'm left with the following questions: 
- Why is the Neo4j browser that much faster without the index? (And would an Index on :Movie(title) speed up the Symfony-side query?)
- While Symfony (Neo4j tab) profiler indicates the pure query time is >1000ms, would it make a difference to speed up the symfony-part by moving to prod? (i.e. is Query-time in the Neo4j tab influenced by moving to prod?)

O, and I'm sorry to have posted here, because it's the movies-symfony-php-bolt project I've tested this with. (After seeing my own project yielded the same query times.)

**Comment by theUm** [comment]
Hi. Currently I`m using php-ogm + this bundle for this project. I have ~20k nodes of same label for speed testing purposes. They have mapping in OGM entities. I`m in symfony DEV mode now.
Simple query like `MATCH (fv:FieldValue) WHERE fv.webPath is not null RETURN fv limit 500`  where fv have around 6 attribs in neo4j browser takes 50 -150 ms and in PHP  - around 80ms with bolt protocol and ~130 
 via HTTP. And its without indexes.
I`m using docker  on VM, neo4j and php containers are linked, like if php and neo4j would be on single machine.
May be try to switch to bolt protocol if you didn`t do that, 1000 ms is quite long time to single query.

**Comment by sfdreverman** [comment]
Lesson learnt. A crappy local DNS resolver could increase handling time by 1 second. :-)
The BOLT server setting was "localhost", when I changed it to "127.0.0.1", the queries dropped to 25ms.
