### ISSUE TITLE
Symfony Flex doesn't support this twig syntax anymore

### ISSUE THREAD

**Issue by TNAJanssen** [neo4j-contrib/neo4j-symfony#34]
https://github.com/neo4j-contrib/neo4j-symfony/blob/6cb661397d1b20b3d12307ade3044105dc4249cf/Resources/config/data-collector.xml#L10

**Comment by TNAJanssen** [comment]
http://symfony.com/doc/current/templating/namespaced_paths.html

Change it to  <tag name="data_collector" template="@Neo4j/webprofiler.html.twig" priority="200" id="neo4j"/>

**Comment by TNAJanssen** [comment]
Can somebody change this?

**Comment by xavismeh** [comment]
Closed by #38. Thank you @TNAJanssen !
