### ISSUE TITLE
connecting to graphenedb fails with "Error receiving data"

### ISSUE THREAD

**Issue by sfdreverman** [neo4j-contrib/neo4j-symfony#37]
As a test, I've recently created a graphenedb instance in the cloud. 

I've filled in the remote connection strings in the config.yml and then I get an "Error receiving data", with no clue what part of the connection is not established. 
The scheme, host and port are correct because if I change them, they give a different error.

Changing the user or password results in error. Reading the graphene PHP guide, it appears to need a _TLS required_ setting. How do I check if this is set? And how do I determine what part of the connection string causes the error?

**Comment by xavismeh** [comment]
Hello @sfdreverman, I think you should post your issue on the https://github.com/graphaware/neo4j-bolt-php repository since this bundle is just an enhancer for a usage with Symfony.

**Comment by sfdreverman** [comment]
True, but the problem is that I don't have access to the call that builds the connection (I just call getClient)... so I wondered if there is a way to specify or configure (from Symfony) that I need a TLS connection?
