### ISSUE TITLE
Neo4jDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by magicuniverse-azeem** [neo4j-contrib/neo4j-symfony#44]
Getting following error when tried this on Symfony4
```
In Neo4jDataCollector.php line 90:
Error: Class Neo4j\Neo4jBundle\Collector\Neo4jDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset)
```

**Comment by Nyholm** [comment]
Thank you. 

Could you maybe send a PR to implement the `reset` function?

**Comment by magicuniverse-azeem** [comment]
@Nyholm it seems there is already an open PR for this. See #43

**Comment by Nyholm** [comment]
Great. I just merged that PR. Can you test it out one last time and I'll be happy to tag a new version.

**Comment by angelov** [comment]
Is there any plan for a new release that will contain the fix for this?

**Comment by magicuniverse-azeem** [comment]
@Nyholm it works, though, I'm curious about his comment, 

> "I'm not sure if the resetting of the QueryLogger is actually needed."

**Comment by Nyholm** [comment]
It is. You do not want to have anything that grows indefinitely.
