### ISSUE TITLE
Recipe for Symfony 4

### ISSUE THREAD

**Issue by HEKET313** [neo4j-contrib/neo4j-symfony#51]
Pls add recipe for your bundle here: https://github.com/symfony/recipes-contrib
So your flex will be able to copy your bundle's default config to `config/packages` folder automatically

**Comment by Nyholm** [comment]
There is an open PR here: https://github.com/symfony/recipes-contrib/pull/115

@xavismeh will just add a minor thing to it and it will be merged. Feel free to help @xavismeh if you want to. If you open a new PR on https://github.com/symfony/recipes-contrib I'll be happy to merge it.

**Comment by Nyholm** [comment]
I've now merged https://github.com/symfony/recipes-contrib/pull/115
