### ISSUE TITLE
Change port to scalarNode in Config

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/neo4j-symfony#53]
Hi @Nyholm ,

Is it advisable to you that we change the config for the port setting from integerNode to scalarNode ?

https://github.com/neo4j-contrib/neo4j-symfony/blob/master/DependencyInjection/Configuration.php#L90

The use case is when the port is passed via the env and sf 3.3 does not support casting of string values.

**Comment by Nyholm** [comment]
This is fixed in #54
