### ISSUE TITLE
add EntityManagerInterface::createQuery 

### ISSUE THREAD

**Issue by glembus** [neo4j-contrib/neo4j-symfony#60]
EntityManagerInterface method createQuery is missed. EntityManager have it. Can be problems with some code checkers in this case.

**Comment by xavismeh** [comment]
Hello,

I think you are talking about a piece of code part of [graphaware/neo4j-php-ogm](https://github.com/graphaware/neo4j-php-ogm) aren't you?

**Comment by glembus** [comment]
Oh, sorry yes. My fault. :) missed this on code rewiev.

**Comment by glembus** [comment]
If inject as EntityManagerInterface code can't pass phpstan.
