### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by johnkendall** [neo4j-contrib/neo4j-symfony#69]
Using the instructions in the readme it doesn't install.
Composer require neo4j/neo4j-bundle

"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for neo4j/neo4j-bundle ^0.4.2 -> satisfiable by neo4j/neo4j-bundle[0.4.2].
    - neo4j/neo4j-bundle 0.4.2 requires symfony/dependency-injection  ^2.8.3 || ^3.0.3 || ^4.0 -> no matching package found."

Installed version of dependency-injection is 5.1.2

**Comment by CodingByJerez** [comment]
the bundle it hasn't been updated for symfony 5 :/

**Comment by Alexandre-T** [comment]
@CodingByJerez , @johnkendall : I have submitted a pull-request for symfony5.

I hope it could be merged.

**Comment by xavismeh** [comment]
Will review https://github.com/neo4j-contrib/neo4j-symfony/pull/70 shortly ! Thanks for this @Alexandre-T

**Comment by Nyholm** [comment]
Fixed in master
